### ISSUE TITLE
Creature: Bad UX when selecting genus

### ISSUE THREAD

**Issue by Lenni009** [Lenni009/HubWikiPageCreator#412]
You first need to select the ecosystem, then the genus.

The genus input is above the ecosystem input though, thus destroying the natural user flow.

**Comment by Lenni009** [comment]
The reason for putting genus above ecosystem was that there is a header "The following information can be found in the creature discovery menu.". This is not true for genus. It would be clearer if we could group inputs -> [Subgrid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Subgrid) with border?

**Comment by Lenni009** [comment]
Subgrid works.
Subgrid class:
```css
.subgrid {
	display: grid;
	grid-template-columns: subgrid;
	border: 1px solid red;
	grid-column: 1/span 2;
	gap: 0;
}
```
